/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-03-06 06:34:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1741220913998L));
    _jspx_dependants.put("jar:file:/C:/Workspace/08_MyBatis/mybatisProject/src/main/webapp/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1741242848317L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".outer {\r\n");
      out.write("   background: rgb(137, 181, 248);\r\n");
      out.write("   color: rgb(65, 64, 64);\r\n");
      out.write("   width: 1000px;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   margin-top: 50px;\r\n");
      out.write("   padding: 10px 0px 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".outer table {\r\n");
      out.write("   margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 5.3.3 -->\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("<style>\r\n");
      out.write("    .login-area a{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-area{\r\n");
      out.write("        background: black;\r\n");
      out.write("        color: white;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    .menu{\r\n");
      out.write("        display: table-cell;\r\n");
      out.write("        width: 250px;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("	    .menu a {\r\n");
      out.write("	   color: white;\r\n");
      out.write("	   font-size: 20px;\r\n");
      out.write("	   font-weight: bold;\r\n");
      out.write("	   text-align: center;\r\n");
      out.write("	   width: 100%;\r\n");
      out.write("	   height: 100%;\r\n");
      out.write("	   line-height: 50px;\r\n");
      out.write("	}\r\n");
      out.write("    .outer{\r\n");
      out.write("    	width: 900px;\r\n");
      out.write("    	background: black;\r\n");
      out.write("    	color: white;\r\n");
      out.write("    	margin: auto;\r\n");
      out.write("    	margin-top: 50px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <h1 align=\"center\">welcome to Mybatis World</h1>\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"login-area\" align=\"right\">\r\n");
      out.write("       ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"nav-area\" align=\"center\">\r\n");
      out.write("        <div class=\"menu\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">HOME</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"menu\">\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">공지사항</a></div>\r\n");
      out.write("        <div class=\"menu\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">게시판</a></div>\r\n");
      out.write("        <div class=\"menu\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">ETC</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div class=\"outer\">\r\n");
      out.write("      <br>\r\n");
      out.write("      <h2 align=\"center\">내 정보</h2>\r\n");
      out.write("      <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/update.me\"\r\n");
      out.write("         method=\"post\" id=\"update-form\">\r\n");
      out.write("         <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td> 아이디</td>\r\n");
      out.write("               <td><input type=\"text\" name=\"userId\" maxlength=\"15\" readonly\r\n");
      out.write("                  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>이름</td>\r\n");
      out.write("               <td><input type=\"text\" name=\"userName\" maxlength=\"8\" readonly\r\n");
      out.write("                  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>전화번호</td>\r\n");
      out.write("               <td><input type=\"text\" name=\"phone\" placeholder=\"- 포함해서 입력\"\r\n");
      out.write("                  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.phone}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>이메일</td>\r\n");
      out.write("               <td><input type=\"text\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>주소</td>\r\n");
      out.write("               <td><input type=\"text\" name=\"address\"\r\n");
      out.write("                  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.address}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>생년월일</td>\r\n");
      out.write("               <td><input type=\"text\" name=\"birthday\"\r\n");
      out.write("                  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.birthday}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("               <td></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("			   <td>성별</td>\r\n");
      out.write("			   <td>\r\n");
      out.write("			      <label>\r\n");
      out.write("			         <input type=\"radio\" name=\"gender\" value=\"M\" \r\n");
      out.write("			            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.gender == 'M' ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("> 남\r\n");
      out.write("			      </label>\r\n");
      out.write("			      <label>\r\n");
      out.write("			         <input type=\"radio\" name=\"gender\" value=\"F\" \r\n");
      out.write("			            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.gender == 'F' ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("> 여\r\n");
      out.write("			      </label>\r\n");
      out.write("			   </td>\r\n");
      out.write("			   <td></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("         </table>\r\n");
      out.write("         </form>\r\n");
      out.write("         \r\n");
      out.write("         <!-- 비밀번호 변경 모달 -->\r\n");
      out.write("         <div class=\"modal\" id=\"myModal\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("               <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                  <!-- Modal Header -->\r\n");
      out.write("                  <div class=\"modal-header\">\r\n");
      out.write("                     <h4 class=\"modal-title\">비밀번호 변경</h4>\r\n");
      out.write("                     <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <!-- Modal body -->\r\n");
      out.write("                  <div class=\"modal-body\">\r\n");
      out.write("                     <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/updatePwd.me\" method=\"post\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"userNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userNo}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("                        <table align=\"center\">\r\n");
      out.write("                           <tr>\r\n");
      out.write("                              <td>현재 비밀번호</td>\r\n");
      out.write("                              <td><input type=\"password\" name=\"userPwd\" required></td>\r\n");
      out.write("                           </tr>\r\n");
      out.write("                           <tr>\r\n");
      out.write("                              <td>변경할 비밀번호</td>\r\n");
      out.write("                              <td><input type=\"password\" name=\"updatePwd\" required></td>\r\n");
      out.write("                           </tr>\r\n");
      out.write("                           <tr>\r\n");
      out.write("                              <td>변경할 비밀번호 확인</td>\r\n");
      out.write("                              <td><input type=\"password\" name=\"checkPwd\" required></td>\r\n");
      out.write("                           </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button id=\"edit-pwd-btn\" type=\"submit\" class=\"btn btn-sm btn-primary\">비밀번호변경</button>\r\n");
      out.write("                     </form>\r\n");
      out.write("\r\n");
      out.write("                            <script>\r\n");
      out.write("                                document.getElementById('edit-pwd-btn').onclick = function(){\r\n");
      out.write("                                    const pwd = document.querySelector(\"#myModal input[name=updatePwd]\").value;\r\n");
      out.write("                                    const pwdCheck = document.querySelector(\"#myModal input[name=checkPwd]\").value;\r\n");
      out.write("\r\n");
      out.write("                                    if(pwd !== pwdCheck){\r\n");
      out.write("                                        alert(\"변경할 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("                                         return false;\r\n");
      out.write("                                          }\r\n");
      out.write("                                }\r\n");
      out.write("                            </script>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <!-- Modal footer -->\r\n");
      out.write("                  <div class=\"modal-footer\">\r\n");
      out.write("                     <button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("                        data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <br> <br>\r\n");
      out.write("		 \r\n");
      out.write("		 <!-- 회원탈퇴 모달 -->\r\n");
      out.write("<div class=\"modal\" id=\"deletemodal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">회원탈퇴</h4>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/delete.me\" method=\"post\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"userNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userNo}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("                        <table>\r\n");
      out.write("                           <tr rowspan=\"2\">\r\n");
      out.write("                              <td colspan=\"2\">탈퇴하기 버튼 클릭시\r\n");
      out.write("   									탈퇴 후 복구가 불가능합니다. <br>\r\n");
      out.write("   									</td>			\r\n");
      out.write("                           </tr>\r\n");
      out.write("                           <tr>\r\n");
      out.write("                           <td align=\"center\">정말 탈퇴하시겠습니까?</td>\r\n");
      out.write("                           </tr>\r\n");
      out.write("                           <tr><td colspan=\"2\"><br></td></tr>\r\n");
      out.write("                           <tr>\r\n");
      out.write("                              <td>비밀번호 입력 : </td>\r\n");
      out.write("                              <td><input type=\"password\" name=\"userPwd\" required></td>\r\n");
      out.write("                           </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button id=\"delete-pwd-btn\" type=\"submit\" class=\"btn btn-sm btn-primary\">탈퇴하기</button>\r\n");
      out.write("                     </form>\r\n");
      out.write("                \r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal footer -->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\">닫기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("         <div align=\"center\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-success\">정보수정</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-small btn-warning\"\r\n");
      out.write("               data-bs-toggle=\"modal\" data-bs-target=\"#myModal\">비밀번호변경</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-small btn-danger\"\r\n");
      out.write("            data-bs-toggle=\"modal\" data-bs-target=\"#deletemodal\">회원탈퇴</button>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- \r\n");
      out.write("   		탈퇴하기 버튼 클릭시\r\n");
      out.write("   		탈퇴 후 복구가 불가능합니다.\r\n");
      out.write("   		정말 탈퇴하시겠습니까?\r\n");
      out.write("   		비밀번호 : \r\n");
      out.write("   		탈퇴하기버튼 -> delete.me\r\n");
      out.write("   		=> /delete.me받은 서버는 비밀번호가 맞는지 확인 후 status -> N으로 변경하고 로그아웃처리\r\n");
      out.write("    -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("       ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("       	");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /views/common/menubar.jsp(67,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginUser}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("	        <form action=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/login.me\" method=\"post\">\r\n");
        out.write("		        <table>\r\n");
        out.write("		            <tr>\r\n");
        out.write("		                <td>아이디</td>\r\n");
        out.write("		                <td><input type=\"text\" name=\"userId\" required></td>\r\n");
        out.write("		                <td rowspan=\"2\"><button type=\"submit\" style=\"height: 50px;\">로그인</button></td>\r\n");
        out.write("		            </tr>\r\n");
        out.write("		            <tr>\r\n");
        out.write("		                <td>비밀번호</td>\r\n");
        out.write("		                <td><input type=\"password\" name=\"userPwd\" required></td>\r\n");
        out.write("		                \r\n");
        out.write("		            </tr>\r\n");
        out.write("		            <tr>\r\n");
        out.write("		                <td colspan=\"3\" align=\"center\">\r\n");
        out.write("		                    <a href=\"enrollForm.me\">회원가입</a>\r\n");
        out.write("		                    <a href=\"\">아이디/비번찾기</a>\r\n");
        out.write("		                </td> \r\n");
        out.write("		            </tr>\r\n");
        out.write("	            </table>\r\n");
        out.write("	        </form>\r\n");
        out.write("     	");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        	<!-- 로그인후 -->\r\n");
        out.write("	        <div>\r\n");
        out.write("	            <table>\r\n");
        out.write("	                <tr>\r\n");
        out.write("	                    <td colspan=\"2\">\r\n");
        out.write("	                        <h3>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userName }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("님 환영합니다. </h3>\r\n");
        out.write("	                    </td>\r\n");
        out.write("	                    <td></td>\r\n");
        out.write("	                </tr>\r\n");
        out.write("	                <tr>\r\n");
        out.write("	                    <td><a href=\"mypage.me\">마이페이지</a></td>\r\n");
        out.write("	                    <td><a href=\"logout.me\">로그아웃</a></td>\r\n");
        out.write("	                </tr>\r\n");
        out.write("	            </table>\r\n");
        out.write("	        </div>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
