CREATE TABLE TEST(
    TNO NUMBER,
    TNAME VARCHAR2(20),
    TDATE DATE
    );

SELECT * FROM TEST;

ALTER TABLE TEST RENAME COLUMN TDATA TO TDATE;

CREATE TABLE SELF(
    TNO NUMBER,
    TNAME VARCHAR2(20),
    TDATE DATE
    );
    
SELECT * FROM SELF;

SELECT * FROM MEMBER;