DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    USERNO	NUMBER PRIMARY KEY, --번호
    USERID	VARCHAR2(15 BYTE) NOT NULL UNIQUE, --아이디
    USERPWD	VARCHAR2(15 BYTE) NOT NULL, -- 비밀번호
    USERNAME VARCHAR2(20 BYTE) NOT NULL, --이름
    GENDER	CHAR(1 BYTE) CHECK(GENDER IN ('M','F')), --성별
    AGE	NUMBER, --나이
    EMAIL	VARCHAR2(30 BYTE), --이메일
    PHONE	CHAR(11 BYTE), --전화번호
    ADDRESS	VARCHAR2(100 BYTE), --주소
    HOBBY	VARCHAR2(50 BYTE), --취미
    ENROLLDATE	DATE DEFAULT SYSDATE NOT NULL --가입일
);

DROP SEQUENCE SEQ_USERNO;
CREATE SEQUENCE SEQ_USERNO
NOCACHE;

