INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '첫 번째 게시글', '이것은 첫 번째 게시글의 내용입니다.', 1, 10, SYSDATE, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 20, '멋진 풍경 사진', '이곳은 아름다운 풍경 사진을 공유하는 공간입니다.', 2, 5, SYSDATE - 1, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 30, '오라클 SQL 기초', '오라클 SQL 기초 강좌를 진행합니다.', 3, 20, SYSDATE - 2, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '귀여운 강아지 사진', '강아지 사진을 공유합니다.', 2, 12, SYSDATE - 3, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 20, 'IT 뉴스 공유', '최신 IT 뉴스를 공유합니다.', 3, 30, SYSDATE - 4, 'N');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 30, '사진 촬영 팁', '사진 촬영 시 유용한 팁을 공유합니다.', 2, 15, SYSDATE - 5, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '자유게시판 이용 규칙', '이 게시판의 이용 규칙을 안내드립니다.', 1, 40, SYSDATE - 6, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 20, '야경 사진 공유', '야경 사진을 촬영해서 공유합니다.', 2, 25, SYSDATE - 7, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 30, '개발자 필독 도서', '개발자가 읽으면 좋은 책을 추천합니다.', 3, 18, SYSDATE - 8, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '나의 반려동물 사진', '반려동물 사진을 공유하는 게시글입니다.', 1, 8, SYSDATE - 9, 'N');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 20, '오늘의 뉴스', '오늘의 핫 이슈 뉴스를 공유합니다.', 3, 35, SYSDATE - 10, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 30, '인물 사진 촬영 팁', '인물 사진을 예쁘게 찍는 방법을 공유합니다.', 2, 22, SYSDATE - 11, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '질문과 답변', '여러분의 질문을 받고 답변하는 게시판입니다.', 1, 50, SYSDATE - 12, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 20, '맛집 사진 공유', '맛있는 음식을 공유하는 게시판입니다.', 2, 13, SYSDATE - 13, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 30, '프로그래밍 언어 비교', '다양한 프로그래밍 언어를 비교 분석합니다.', 3, 27, SYSDATE - 14, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '고양이 사진 자랑', '고양이 사진을 올려주세요!', 3, 17, SYSDATE - 15, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 20, '최신 IT 트렌드', '최근 IT 업계의 트렌드를 분석합니다.', 3, 28, SYSDATE - 16, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 30, '여행 사진 공유', '여행에서 찍은 멋진 사진을 공유합니다.', 3, 32, SYSDATE - 17, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '자유 게시판', '무엇이든 자유롭게 이야기하세요.', 1, 45, SYSDATE - 18, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 20, '멋진 풍경 사진', '풍경 사진을 감상해보세요.', 2, 11, SYSDATE - 19, 'N');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 30, '프로그래밍 입문', '초보자를 위한 프로그래밍 강좌입니다.', 3, 19, SYSDATE - 20, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '내 애완동물 사진', '내 반려동물 사진을 공유합니다.', 2, 21, SYSDATE - 21, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 20, '오늘의 이슈', '오늘 가장 핫한 이슈를 소개합니다.', 1, 33, SYSDATE - 22, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 30, '예쁜 꽃 사진', '다양한 꽃 사진을 공유합니다.', 3, 14, SYSDATE - 23, 'Y');

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER, COUNT, CREATE_DATE, STATUS)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '자유롭게 대화해요', '친구들과 자유롭게 이야기하는 공간입니다.', 1, 29, SYSDATE - 24, 'Y');

COMMIT;
