--8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR 
JOIN TB_CLASS_PROFESSOR  USING(PROFESSOR_NO)
JOIN TB_CLASS USING(CLASS_NO)
ORDER BY CLASS_NAME;

--9. 
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR 
JOIN TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_CLASS C USING(CLASS_NO)
JOIN TB_DEPARTMENT D ON C.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE CATEGORY = '인문사회'
ORDER BY CLASS_NAME;

--10. 
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT),1)
FROM TB_STUDENT S
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY STUDENT_NO;

--11.
SELECT DEPARTMENT_NAME AS 학과이름, STUDENT_NAME AS 학생이름, PROFESSOR_NAME AS 지도교수이름
FROM TB_DEPARTMENT 
JOIN TB_STUDENT S USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
WHERE S.STUDENT_NO = 'A313047';

--12.
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE G USING(STUDENT_NO)
JOIN TB_CLASS C ON G.CLASS_NO = C.CLASS_NO
WHERE CLASS_NAME = '인간관계론' AND TERM_NO LIKE '2007%';

--13.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR P ON C.CLASS_NO = P.CLASS_NO
WHERE CATEGORY='예체능' AND PROFESSOR_NO IS NULL; 

--14. 
SELECT STUDENT_NAME AS "학생이름", CASE
        WHEN PROFESSOR_NAME IS NULL THEN '지도교수 미지정' 
        ELSE PROFESSOR_NAME
        END AS "지도교수"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR P ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
WHERE DEPARTMENT_NAME = '서반아어학과';

--15.
SELECT STUDENT_NO AS "학번" , STUDENT_NAME AS "이름", 
       DEPARTMENT_NAME AS "학과 이름", AVG(POINT) AS "평점"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE G ON S.STUDENT_NO = G.STUDENT_NO
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) >= 4;

CREATE TABLE PHOTOBOARD (
    PBOARD_NO NUMBER PRIMARY KEY,
    UPLOADER VARCHAR2(30),   
    ORIGIN_NAME VARCHAR2(255) NOT NULL,  
    CHANGE_NAME VARCHAR2(255) NOT NULL,  
    FILE_PATH VARCHAR2(1000 BYTE),
    FILE_LEVEL NUMBER CONSTRAINT CHECK_PHOTO CHECK(FILE_LEVEL IN(1,2)),
    UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,      
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))       
);

ALTER TABLE PHOTOBOARD
ADD PHOTO_TITLE VARCHAR2(100);

CREATE SEQUENCE PBOARD_SEQ
START WITH 1           -- 시퀀스의 시작 값
INCREMENT BY 1         -- 증가하는 값
NOCACHE                -- 캐시하지 않음 (선택 사항, 기본값은 CACHE로 설정됨)
NOCYCLE;

ALTER TABLE BOARD RENAME COLUMN PHOTO_CHANGE_NAME TO PHOTO_CHANGE_NAME1;



DELETE 
FROM BOARD
WHERE BOARD_TYPE = 2;

COMMIT;


