-- 매장 데이터 추가 (STORE)
INSERT INTO STORE (STORE_ID, STORE_NAME, STORE_PHONE, STORE_ADDRESS)
VALUES (STORE_SEQ.NEXTVAL, '하남점', '02-1234-5678', '서울시 강남구 테헤란로 123');

INSERT INTO STORE (STORE_ID, STORE_NAME, STORE_PHONE, STORE_ADDRESS)
VALUES (STORE_SEQ.NEXTVAL, '강남점', '02-9876-5432', '서울시 종로구 세종로 45');

INSERT INTO STORE (STORE_ID, STORE_NAME, STORE_PHONE, STORE_ADDRESS)
VALUES (STORE_SEQ.NEXTVAL, '역삼점', '031-1122-3344', '경기도 수원시 영통구 678');

INSERT INTO STORE (STORE_ID, STORE_NAME, STORE_PHONE, STORE_ADDRESS)
VALUES (STORE_SEQ.NEXTVAL, '선릉점', '042-555-1234', '대전광역시 중구 대흥로 22');

-- 카테고리 데이터 추가 (CATEGORY)
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME, STATUS)
VALUES (CATEGORY_SEQ.NEXTVAL, '스니커즈', 'Y');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME, STATUS)
VALUES (CATEGORY_SEQ.NEXTVAL, '샌들', 'Y');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME, STATUS)
VALUES (CATEGORY_SEQ.NEXTVAL, '구두', 'Y');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME, STATUS)
VALUES (CATEGORY_SEQ.NEXTVAL, '부츠', 'Y');

-- 멤버 데이터 추가 (MEMBER)
INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10001', 'admin', 'password123', '관리자', '010-1234-5678', 'admin', 'Y', SYSDATE, SYSDATE, TO_DATE('2023-01-10', 'YYYY-MM-DD'), 5000000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10002', 'user01', 'userpass01', '김철수', '010-9876-5432', 'manager', 'Y', SYSDATE, SYSDATE, TO_DATE('2023-05-15', 'YYYY-MM-DD'), 3200000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10003', 'user02', 'userpass02', '이영희', '010-1111-2222', 'member', 'N', SYSDATE, SYSDATE, TO_DATE('2024-02-01', 'YYYY-MM-DD'), 3000000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10001', 'user03', 'userpass03', '박지훈', '010-3333-4444', 'employee', 'Y', SYSDATE, SYSDATE, TO_DATE('2024-03-15', 'YYYY-MM-DD'), 3100000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10001', 'user04', 'userpass04', '정민수', '010-5555-6666', 'employee', 'Y', SYSDATE, SYSDATE, TO_DATE('2023-09-10', 'YYYY-MM-DD'), 3200000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10001', 'user05', 'userpass05', '최은정', '010-7777-8888', 'manager', 'Y', SYSDATE, SYSDATE, TO_DATE('2022-12-20', 'YYYY-MM-DD'), 4200000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10002', 'user06', 'userpass06', '김다혜', '010-9999-0000', 'employee', 'Y', SYSDATE, SYSDATE, TO_DATE('2024-04-01', 'YYYY-MM-DD'), 2900000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10002', 'user07', 'userpass07', '손현우', '010-1212-3434', 'employee', 'Y', SYSDATE, SYSDATE, TO_DATE('2023-06-25', 'YYYY-MM-DD'), 3000000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10002', 'user08', 'userpass08', '오세진', '010-5656-7878', 'eanager', 'Y', SYSDATE, SYSDATE, TO_DATE('2024-01-05', 'YYYY-MM-DD'), 4000000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10003', 'user09', 'userpass09', '강유나', '010-8989-1010', 'employee', 'Y', SYSDATE, SYSDATE, TO_DATE('2022-11-30', 'YYYY-MM-DD'), 4500000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10003', 'user10', 'userpass10', '배성훈', '010-2323-4545', 'manager', 'Y', SYSDATE, SYSDATE, TO_DATE('2024-03-10', 'YYYY-MM-DD'), 3500000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10004', 'user11', 'userpass11', '이수진', '010-6767-8989', 'employee', 'Y', SYSDATE, SYSDATE, TO_DATE('2023-07-20', 'YYYY-MM-DD'), 3300000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10004', 'user12', 'userpass12', '조한솔', '010-9090-1212', 'employee', 'Y', SYSDATE, SYSDATE, TO_DATE('2024-02-15', 'YYYY-MM-DD'), 3100000);

INSERT INTO MEMBER (EMP_NO, STORE_ID, MEM_ID, MEM_PWD, MEM_NAME, PHONE, POSITION, STATUS, CREATE_DATE, MODIFY_DATE, HIRE_DATE, SALARY)
VALUES (EMP_SEQ.NEXTVAL, '10004', 'admin01', 'adminpass01', '관리자', '010-0000-0000', 'admin', 'Y', SYSDATE, SYSDATE, TO_DATE('2023-01-01', 'YYYY-MM-DD'), 5000000);

-- 공지사항 데이터 추가
INSERT INTO BOARD (BOARD_NO, EMP_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, BOARD_TYPE)
VALUES (BOARD_SEQ.NEXTVAL, 5, '시스템 점검 안내', '2025년 4월 3일 오전 2시부터 6시까지 시스템 점검이 진행됩니다.', TO_DATE('2025-04-02', 'YYYY-MM-DD'), 1);

INSERT INTO BOARD (BOARD_NO, EMP_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, BOARD_TYPE)
VALUES (BOARD_SEQ.NEXTVAL, 1, '프로젝트 완료 보고', '2025년 3분기 프로젝트가 성공적으로 완료되었습니다. 관련 자료는 내부 공유 드라이브에서 확인 바랍니다.', TO_DATE('2025-04-01', 'YYYY-MM-DD'), 2);

INSERT INTO BOARD (BOARD_NO, EMP_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, BOARD_TYPE)
VALUES (BOARD_SEQ.NEXTVAL, 6, '보안 강화 공지', '2025년 4월 10일부터 모든 직원은 보안 강화 프로그램을 실행해야 합니다.', TO_DATE('2025-04-02', 'YYYY-MM-DD'), 1);

INSERT INTO BOARD (BOARD_NO, EMP_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, BOARD_TYPE)
VALUES (BOARD_SEQ.NEXTVAL, 4, '팀 회의 일정', '2025년 4월 5일 오후 3시에 전사 팀 회의가 진행됩니다. 모두 참석 바랍니다.', TO_DATE('2025-04-02', 'YYYY-MM-DD'), 2);

INSERT INTO BOARD (BOARD_NO, EMP_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, BOARD_TYPE)
VALUES (BOARD_SEQ.NEXTVAL, 2, '업데이트 안내', '2025년 4월 6일 시스템 업데이트가 예정되어 있습니다. 주요 변경 사항은 아래와 같습니다...', TO_DATE('2025-04-02', 'YYYY-MM-DD'), 1);

INSERT INTO BOARD (BOARD_NO, EMP_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, BOARD_TYPE)
VALUES (BOARD_SEQ.NEXTVAL, 7, '팀 빌딩 이벤트', '2025년 4월 12일, 팀 빌딩 이벤트가 진행됩니다. 모든 팀원이 참여해야 합니다.', TO_DATE('2025-04-03', 'YYYY-MM-DD'), 2);

INSERT INTO BOARD (BOARD_NO, EMP_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, BOARD_TYPE)
VALUES (BOARD_SEQ.NEXTVAL, 9, '급여 지급 일정', '2025년 4월 5일 급여가 지급됩니다. 각 부서에서는 사전 검토를 부탁드립니다.', TO_DATE('2025-04-03', 'YYYY-MM-DD'), 1);

INSERT INTO BOARD (BOARD_NO, EMP_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, BOARD_TYPE)
VALUES (BOARD_SEQ.NEXTVAL, 8, '업무 매뉴얼 업데이트', '업무 매뉴얼에 대한 최신 업데이트가 완료되었습니다. 새로운 내용은 첨부 파일을 참고하십시오.', TO_DATE('2025-04-02', 'YYYY-MM-DD'), 2);

INSERT INTO BOARD (BOARD_NO, EMP_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, BOARD_TYPE)
VALUES (BOARD_SEQ.NEXTVAL, 10, '기술 세미나 안내', '2025년 4월 8일 기술 세미나가 진행됩니다. 참석 여부를 알려주십시오.', TO_DATE('2025-04-02', 'YYYY-MM-DD'), 1);

INSERT INTO BOARD (BOARD_NO, EMP_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, BOARD_TYPE)
VALUES (BOARD_SEQ.NEXTVAL, 11, '채용 공고', '2025년 4월 10일 신입사원 채용 공고가 발표됩니다. 지원자는 이메일로 제출 바랍니다.', TO_DATE('2025-04-03', 'YYYY-MM-DD'), 2);

-- 거래처 데이터 추가
INSERT INTO CLIENT (CLIENT_ID, CLIENT_NAME, CLIENT_CEO, CLIENT_PHONE, CLIENT_ADDRESS)
VALUES(CLIENT_SEQ.NEXTVAL, '아디다스', '박지민', '010-1111-2222', '대전광역시 땡땡구');

INSERT INTO CLIENT (CLIENT_ID, CLIENT_NAME, CLIENT_CEO, CLIENT_PHONE, CLIENT_ADDRESS)
VALUES(CLIENT_SEQ.NEXTVAL, '나이키', '김현아', '010-3333-4444', '서울특별시 빵빵구');

-- 상품 데이터 추가
INSERT INTO PRODUCT (PRODUCT_NO, CLIENT_ID, CATEGORY_NO, PRODUCT_NAME, COLOR, PRODUCT_SIZE, REGISTRATION_DATE,
                    STOCK_IN_PRICE, STOCK_OUT_PRICE, IMAGE_URL, STATUS)
VALUES (PRODUCT_SEQ.NEXTVAL, '1', '1', '에어포스123', 'WHITE', '220', SYSDATE, 10000, 20000, NULL, 'Y');

INSERT INTO PRODUCT (PRODUCT_NO, CLIENT_ID, CATEGORY_NO, PRODUCT_NAME, COLOR, PRODUCT_SIZE, REGISTRATION_DATE,
                    STOCK_IN_PRICE, STOCK_OUT_PRICE, IMAGE_URL, STATUS)
VALUES (PRODUCT_SEQ.NEXTVAL, '2', '2', '나이키로고운동화', 'BLACK', '250', SYSDATE, 15000, 25000, NULL, 'Y');

INSERT INTO PRODUCT (PRODUCT_NO, CLIENT_ID, CATEGORY_NO, PRODUCT_NAME, COLOR, PRODUCT_SIZE, REGISTRATION_DATE,
                    STOCK_IN_PRICE, STOCK_OUT_PRICE, IMAGE_URL, STATUS)
VALUES (PRODUCT_SEQ.NEXTVAL, '1', '3', '리복스포츠운동화', 'RED', '240', SYSDATE, 5000, 10000, NULL, 'Y');

INSERT INTO PRODUCT (PRODUCT_NO, CLIENT_ID, CATEGORY_NO, PRODUCT_NAME, COLOR, PRODUCT_SIZE, REGISTRATION_DATE,
                    STOCK_IN_PRICE, STOCK_OUT_PRICE, IMAGE_URL, STATUS)
VALUES (PRODUCT_SEQ.NEXTVAL, '2', '1', '에어맥스2025', 'BLUE', '270', SYSDATE, 12000, 24000, NULL, 'Y');

INSERT INTO PRODUCT (PRODUCT_NO, CLIENT_ID, CATEGORY_NO, PRODUCT_NAME, COLOR, PRODUCT_SIZE, REGISTRATION_DATE,
                    STOCK_IN_PRICE, STOCK_OUT_PRICE, IMAGE_URL, STATUS)
VALUES (PRODUCT_SEQ.NEXTVAL, '1', '4', '아디다스운동화', 'GREEN', '280', SYSDATE, 18000, 36000, NULL, 'Y');

INSERT INTO PRODUCT (PRODUCT_NO, CLIENT_ID, CATEGORY_NO, PRODUCT_NAME, COLOR, PRODUCT_SIZE, REGISTRATION_DATE,
                    STOCK_IN_PRICE, STOCK_OUT_PRICE, IMAGE_URL, STATUS)
VALUES (PRODUCT_SEQ.NEXTVAL, '1', '2', '캠프운동화', 'WHITE', '250', SYSDATE, 7000, 15000, NULL, 'Y');

INSERT INTO PRODUCT (PRODUCT_NO, CLIENT_ID, CATEGORY_NO, PRODUCT_NAME, COLOR, PRODUCT_SIZE, REGISTRATION_DATE,
                    STOCK_IN_PRICE, STOCK_OUT_PRICE, IMAGE_URL, STATUS)
VALUES (PRODUCT_SEQ.NEXTVAL, '2', '3', '헬스장운동화', 'BLACK', '290', SYSDATE, 10000, 20000, NULL, 'Y');

INSERT INTO PRODUCT (PRODUCT_NO, CLIENT_ID, CATEGORY_NO, PRODUCT_NAME, COLOR, PRODUCT_SIZE, REGISTRATION_DATE,
                    STOCK_IN_PRICE, STOCK_OUT_PRICE, IMAGE_URL, STATUS)
VALUES (PRODUCT_SEQ.NEXTVAL, '2', '1', '스포츠운동화', 'RED', '220', SYSDATE, 8000, 16000, NULL, 'Y');

INSERT INTO PRODUCT (PRODUCT_NO, CLIENT_ID, CATEGORY_NO, PRODUCT_NAME, COLOR, PRODUCT_SIZE, REGISTRATION_DATE,
                    STOCK_IN_PRICE, STOCK_OUT_PRICE, IMAGE_URL, STATUS)
VALUES (PRODUCT_SEQ.NEXTVAL, '1', '2', '긴팔운동화', 'BLACK', '240', SYSDATE, 10000, 20000, NULL, 'Y');

INSERT INTO PRODUCT (PRODUCT_NO, CLIENT_ID, CATEGORY_NO, PRODUCT_NAME, COLOR, PRODUCT_SIZE, REGISTRATION_DATE,
                    STOCK_IN_PRICE, STOCK_OUT_PRICE, IMAGE_URL, STATUS)
VALUES (PRODUCT_SEQ.NEXTVAL, '2', '4', '쥬니어운동화', 'PINK', '230', SYSDATE, 15000, 30000, NULL, 'Y');

COMMIT;