UPDATE MEMBER
SET STATUS = 'N'
WHERE MEM_NAME = '이영희';

COMMIT;

SELECT
        M.EMP_NO,
        M.CREATE_DATE,
        M.MEM_ID,
        M.MEM_NAME,
        M.PHONE,
        S.STORE_NAME
        FROM MEMBER M
        JOIN STORE S ON M.STORE_ID = S.STORE_ID
        WHERE M.STATUS = 'Y'
              AND S.STATUS = 'N'
              AND M.POSITION = 'employee'
              AND M.STORE_ID = S.STORE_ID
        ORDER BY M.EMP_NO ASC;
        
        
INSERT INTO STORAGE (STORAGE_NO, STORAGE_LOCATION, ABLE_AMOUNT, CURRENT_AMOUNT) VALUES (STORAGE_SEQ.NEXTVAL, '서울창고A', 1000, 500);
INSERT INTO STORAGE (STORAGE_NO, STORAGE_LOCATION, ABLE_AMOUNT, CURRENT_AMOUNT) VALUES (STORAGE_SEQ.NEXTVAL, '서울창고B', 800, 300);
INSERT INTO STORAGE (STORAGE_NO, STORAGE_LOCATION, ABLE_AMOUNT, CURRENT_AMOUNT) VALUES (STORAGE_SEQ.NEXTVAL, '부산창고A', 1200, 900);
INSERT INTO STORAGE (STORAGE_NO, STORAGE_LOCATION, ABLE_AMOUNT, CURRENT_AMOUNT) VALUES (STORAGE_SEQ.NEXTVAL, '부산창고B', 600, 200);
INSERT INTO STORAGE (STORAGE_NO, STORAGE_LOCATION, ABLE_AMOUNT, CURRENT_AMOUNT) VALUES (STORAGE_SEQ.NEXTVAL, '인천창고A', 1500, 1300);
INSERT INTO STORAGE (STORAGE_NO, STORAGE_LOCATION, ABLE_AMOUNT, CURRENT_AMOUNT) VALUES (STORAGE_SEQ.NEXTVAL, '대구창고A', 700, 400);
INSERT INTO STORAGE (STORAGE_NO, STORAGE_LOCATION, ABLE_AMOUNT, CURRENT_AMOUNT) VALUES (STORAGE_SEQ.NEXTVAL, '대전창고A', 900, 600);
INSERT INTO STORAGE (STORAGE_NO, STORAGE_LOCATION, ABLE_AMOUNT, CURRENT_AMOUNT) VALUES (STORAGE_SEQ.NEXTVAL, '광주창고A', 1100, 700);
INSERT INTO STORAGE (STORAGE_NO, STORAGE_LOCATION, ABLE_AMOUNT, CURRENT_AMOUNT) VALUES (STORAGE_SEQ.NEXTVAL, '울산창고A', 500, 200);
INSERT INTO STORAGE (STORAGE_NO, STORAGE_LOCATION, ABLE_AMOUNT, CURRENT_AMOUNT) VALUES (STORAGE_SEQ.NEXTVAL, '제주창고A', 400, 100);

COMMIT;

SELECT *
FROM STORAGE;

SELECT
        EMP_NO,
        STORE_ID,
        MEM_ID,
        MEM_PWD,
        MEM_NAME,
        PHONE,
        POSITION,
        STATUS,
        CREATE_DATE,
        MODIFY_DATE,
        HIRE_DATE,
        SALARY,
        CEIL(SYSDATE - CREATE_DATE) AS WORKDATE
        FROM MEMBER
        
        
INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '김철수', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_IN_REGISTERED', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '이영희', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_IN_REGISTERED', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '박지훈', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_IN_PROGRESS', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '김철수', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_IN_PROGRESS', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '최은정', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_IN_COMPLETED', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '김다혜', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_IN_COMPLETED', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '박지훈', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_OUT_REGISTERED', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '박지훈', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_OUT_REGISTERED', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '이영희', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_OUT_PROGRESS', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '최은정', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_OUT_PROGRESS', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '김철수', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_OUT_COMPLETED', 'Y');

INSERT INTO STOCK (STOCK_NO, STOCK_EMP, STOCK_DATE, EXP_DATE, MODIFY_DATE, STOCK_STATUS, STATUS)
VALUES (STOCK_SEQ.NEXTVAL, '김철수', SYSDATE, SYSDATE + 3, SYSDATE, 'STOCK_OUT_COMPLETED', 'Y');

COMMIT;

ALTER TABLE ATTENDANCE
ADD CLOCK_OUT DATE; 

COMMENT ON COLUMN ATTENDANCE.CLOCK_OUT IS '퇴근시간';
COMMENT ON COLUMN ATTENDANCE.CLOCK_IN IS '출근시간';

ALTER TABLE ATTENDANCE
ADD STORE_ID DATE;


-- 2025-04-01 출퇴근
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 1, TO_DATE('2025-04-01 08:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-01 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 2, TO_DATE('2025-04-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-01 18:10:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 3, TO_DATE('2025-04-01 08:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-01 17:50:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 4, TO_DATE('2025-04-01 09:10:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-01 18:20:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 5, TO_DATE('2025-04-01 08:55:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-01 17:55:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 6, TO_DATE('2025-04-01 09:05:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-01 18:25:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 7, TO_DATE('2025-04-01 08:40:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-01 17:40:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 8, TO_DATE('2025-04-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-01 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 10, TO_DATE('2025-04-01 08:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-01 18:10:00', 'YYYY-MM-DD HH24:MI:SS'));

-- 2025-04-02 출퇴근
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 1, TO_DATE('2025-04-02 08:48:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-02 18:05:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 2, TO_DATE('2025-04-02 09:01:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-02 18:15:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 3, TO_DATE('2025-04-02 08:43:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-02 17:45:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 4, TO_DATE('2025-04-02 09:12:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-02 18:17:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 5, TO_DATE('2025-04-02 08:56:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-02 18:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 6, TO_DATE('2025-04-02 09:07:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-02 18:28:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 7, TO_DATE('2025-04-02 08:38:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-02 17:38:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 8, TO_DATE('2025-04-02 09:02:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-02 18:05:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 10, TO_DATE('2025-04-02 08:52:00', 'YYYY-MM-DD HH24:MI:SS'), 'L', TO_DATE('2025-04-02 18:08:00', 'YYYY-MM-DD HH24:MI:SS'));

-- 2025-04-03 출근만
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 1, TO_DATE('2025-04-03 08:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'W', NULL);
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 2, TO_DATE('2025-04-03 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'W', NULL);
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 3, TO_DATE('2025-04-03 08:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'W', NULL);
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 4, TO_DATE('2025-04-03 09:10:00', 'YYYY-MM-DD HH24:MI:SS'), 'W', NULL);
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 5, TO_DATE('2025-04-03 08:55:00', 'YYYY-MM-DD HH24:MI:SS'), 'W', NULL);
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 6, TO_DATE('2025-04-03 09:05:00', 'YYYY-MM-DD HH24:MI:SS'), 'W', NULL);
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 7, TO_DATE('2025-04-03 08:40:00', 'YYYY-MM-DD HH24:MI:SS'), 'W', NULL);
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 8, TO_DATE('2025-04-03 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'W', NULL);
INSERT INTO ATTENDANCE (ATTENDANCE_NO, EMP_NO, CLOCK_IN, STATUS, CLOCK_OUT) VALUES (ATTENDANCE_SEQ.NEXTVAL, 10, TO_DATE('2025-04-03 08:50:00', 'YYYY-MM-DD HH24:MI:SS'), 'W', NULL);

COMMIT;

SELECT * FROM ATTENDANCE WHERE EMP_NO = 5;

 SELECT CLOCK_OUT - CLOCK_IN AS WORKTIME
 FROM ATTENDANCE
 WHERE EMP_NO = 5
 ORDER BY ATTENDANCE_NO DESC;
 
                SELECT
                a.ATTENDANCE_NO,
                a.EMP_NO,
                m.MEM_NAME AS EMP_NAME,
                a.CLOCK_IN,
                a.CLOCK_OUT,
                TRUNC(a.CLOCK_IN) AS WORKDAY,
                a.STATUS,
                CASE
                WHEN a.CLOCK_OUT IS NOT NULL THEN
                TO_CHAR(FLOOR((a.CLOCK_OUT - a.CLOCK_IN) * 24)) || '시간 ' ||
                TO_CHAR(FLOOR(MOD((a.CLOCK_OUT - a.CLOCK_IN) * 24 * 60, 60))) || '분'
                ELSE NULL
                END AS WORKTIME
        FROM ATTENDANCE a
        JOIN MEMBER m ON a.EMP_NO = m.EMP_NO
        WHERE m.STORE_ID = 10001
        AND TRUNC(a.CLOCK_IN) = TRUNC(SYSDATE)
        ORDER BY a.ATTENDANCE_NO DESC
        
        ALTER TABLE CLIENT ADD STATUS CHAR(1) DEFAULT 'Y' NOT NULL;
        
        ALTER SEQUENCE ATTENDANCE_SEQ INCREMENT BY +1;